import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primarylight dark:bg-primary`}
        id="parent"
      >
        <div
          id="up"
          className="main-container relative z-10 overflow-hidden bg-seconderylight dark:bg-secondery border-2 border-borderlight dark:border-border container  mx-auto px-4 sm:px-16  "
        >
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
